/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AIChat: typeof import('./src/components/AIChat.vue')['default']
    AIMessage: typeof import('./src/components/AIMessage.vue')['default']
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutRange: typeof import('nutui-uniapp/components/range/range.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    SendBox: typeof import('./src/components/SendBox.vue')['default']
    SendBox_ss3: typeof import('./src/components/SendBox_ss3.vue')['default']
    SendBox_sse: typeof import('./src/components/SendBox_sse.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Settings_org: typeof import('./src/components/Settings_org.vue')['default']
    TypeWriter: typeof import('./src/components/TypeWriter.vue')['default']
  }
}
